// User types
export interface User {
  id: string;
  email: string;
  username: string;
  name?: string;
  bio?: string;
  avatar?: string;
  /** Stacks (STX) wallet address — generated by Hiro Wallet — starts with SP (mainnet) or ST (testnet) */
  walletAddress: string;
  emailVerified: boolean;
  followersCount: number;
  followingCount: number;
  postsCount: number;
  language?: string;
  createdAt: string;
}

// Post types
export interface Post {
  id: string;
  /** On-chain post ID (uint from linkup-posts contract) */
  onChainId?: number;
  /** Gaia URL where full content is stored */
  gaiaUrl?: string;
  /** SHA-256 content hash stored on-chain */
  contentHash?: string;
  author: {
    _id: string;
    username: string;
    name?: string;
    avatar?: string;
  };
  content: string;
  images: string[];
  likesCount: number;
  commentsCount: number;
  sharesCount: number;
  tipsCount: number;
  totalTipsAmount: number;
  isLiked: boolean;
  isTokenized: boolean;
  tokenMintAddress?: string;
  tokenSupply: number;
  tokenPrice: number;
  tokenHolders: number;
  createdAt: string;
  updatedAt: string;
}

// Comment types
export interface Comment {
  id: string;
  author: {
    _id: string;
    username: string;
    name?: string;
    avatar?: string;
  };
  post: string;
  parentComment?: string;
  content: string;
  likesCount: number;
  repliesCount: number;
  createdAt: string;
}

// Chat types
export interface Chat {
  id: string;
  participants: User[];
  otherParticipant: User;
  lastMessage?: string;
  lastMessageAt?: string;
  lastMessageBy?: User;
}

export interface Message {
  id: string;
  chatId: string;
  /** Stacks wallet address of sender */
  senderAddress: string;
  content: string;
  type: 'text' | 'payment';
  /** Amount in micro-STX */
  paymentAmount?: number;
  /** Stacks transaction ID for payment messages */
  paymentTxId?: string;
  createdAt: number; // unix ms
  /** True if this message was sent by the current user */
  isMine?: boolean;
}

// Transaction types
export interface Transaction {
  txId: string;
  type: 'send' | 'receive' | 'contract_call';
  /** Amount in micro-STX */
  amount: number;
  fromAddress?: string;
  toAddress?: string;
  status: 'pending' | 'success' | 'failed' | 'abort_by_response' | 'abort_by_post_condition';
  blockTime?: string;
  fee?: number;
  blockHeight?: number;
}

// Wallet types
export interface WalletBalance {
  walletAddress: string;
  /** Balance in micro-STX */
  balance: number;
  /** Balance in STX (balance / 1_000_000) */
  balanceStx: number;
}

// Payment types
export interface PaymentQR {
  address: string;
  amount: number | null;
  label: string;
  message: string;
}

// Notification types
export interface Notification {
  id: string;
  recipient: string;
  sender: {
    _id: string;
    username: string;
    name?: string;
    avatar?: string;
  };
  type: 'like' | 'comment' | 'follow' | 'tip' | 'token_purchase' | 'mention' | 'payment_received';
  post?: {
    _id: string;
    content: string;
  };
  message: string;
  isRead: boolean;
  amount?: number;
  signature?: string;
  createdAt: string;
}

// Portfolio types
export interface PortfolioHolding {
  id: string;
  post: Post;
  amount: number;
  purchasePrice: number;
  currentPrice: number;
  totalInvested: number;
  currentValue: number;
  profitLoss: number;
  profitLossPercentage: number;
}

export interface Portfolio {
  totalValue: number;
  totalInvested: number;
  totalProfitLoss: number;
  totalProfitLossPercentage: number;
  holdings: PortfolioHolding[];
}
