import fs from 'fs';
import path from 'path';

const localesDir = path.join(process.cwd(), 'locales');

// New translation keys for send and history screens
const newKeys = {
  wallet: {
    // Send screen keys
    sendSol: 'Send SOL',
    availableBalance: 'Available Balance',
    recipientAddress: 'Recipient Address',
    enterSolanaAddress: 'Enter Solana wallet address',
    scanQr: 'Scan QR',
    contacts: 'Contacts',
    amountSol: 'Amount (SOL)',
    memoOptional: 'Memo (Optional)',
    addNote: 'Add a note...',
    transactionDetails: 'Transaction Details',
    network: 'Network',
    networkFee: 'Network Fee',
    confirmTransaction: 'Confirm Transaction',
    verifyAddress: 'Please verify the recipient address. Transactions cannot be reversed.',
    selectContact: 'Select Contact',
    searchByUsername: 'Search by username or name...',
    noUsersFound: 'No users found',
    searchForUsers: 'Search for users to send SOL',
    positionQrCode: 'Position the QR code within the frame',
    addressScanned: 'Address scanned!',
    cameraPermissionRequired: 'Camera permission is required to scan QR codes',
    selected: 'Selected',
    paymentTo: 'Payment to',
    
    // Validation messages
    pleaseEnterValidAmount: 'Please enter a valid amount',
    amountMustBeGreaterThanZero: 'Amount must be greater than 0',
    insufficientBalanceYouHave: 'Insufficient balance. You have {{balance}} SOL',
    pleaseEnterRecipientAddress: 'Please enter a recipient address',
    invalidSolanaAddress: 'Invalid Solana address',
    
    // Transaction history keys
    transactionHistory: 'Transaction History',
    noTransactionsYet: 'No transactions yet',
    noMoreTransactions: 'No more transactions',
    
    // Transaction types and statuses (already exist but adding for completeness)
    swap: 'Swap',
    airdrop: 'Airdrop'
  }
};

// Translation mappings for each language
const translations: Record<string, typeof newKeys> = {
  es: {
    wallet: {
      sendSol: 'Enviar SOL',
      availableBalance: 'Saldo Disponible',
      recipientAddress: 'Dirección del Destinatario',
      enterSolanaAddress: 'Ingrese la dirección de billetera Solana',
      scanQr: 'Escanear QR',
      contacts: 'Contactos',
      amountSol: 'Cantidad (SOL)',
      memoOptional: 'Nota (Opcional)',
      addNote: 'Agregar una nota...',
      transactionDetails: 'Detalles de la Transacción',
      network: 'Red',
      networkFee: 'Tarifa de Red',
      confirmTransaction: 'Confirmar Transacción',
      verifyAddress: 'Por favor verifique la dirección del destinatario. Las transacciones no se pueden revertir.',
      selectContact: 'Seleccionar Contacto',
      searchByUsername: 'Buscar por nombre de usuario o nombre...',
      noUsersFound: 'No se encontraron usuarios',
      searchForUsers: 'Buscar usuarios para enviar SOL',
      positionQrCode: 'Posicione el código QR dentro del marco',
      addressScanned: '¡Dirección escaneada!',
      cameraPermissionRequired: 'Se requiere permiso de cámara para escanear códigos QR',
      selected: 'Seleccionado',
      paymentTo: 'Pago a',
      pleaseEnterValidAmount: 'Por favor ingrese una cantidad válida',
      amountMustBeGreaterThanZero: 'La cantidad debe ser mayor que 0',
      insufficientBalanceYouHave: 'Saldo insuficiente. Tienes {{balance}} SOL',
      pleaseEnterRecipientAddress: 'Por favor ingrese una dirección de destinatario',
      invalidSolanaAddress: 'Dirección de Solana inválida',
      transactionHistory: 'Historial de Transacciones',
      noTransactionsYet: 'Aún no hay transacciones',
      noMoreTransactions: 'No hay más transacciones',
      swap: 'Intercambio',
      airdrop: 'Airdrop'
    }
  },
  fr: {
    wallet: {
      sendSol: 'Envoyer SOL',
      availableBalance: 'Solde Disponible',
      recipientAddress: 'Adresse du Destinataire',
      enterSolanaAddress: 'Entrez l\'adresse du portefeuille Solana',
      scanQr: 'Scanner QR',
      contacts: 'Contacts',
      amountSol: 'Montant (SOL)',
      memoOptional: 'Note (Optionnel)',
      addNote: 'Ajouter une note...',
      transactionDetails: 'Détails de la Transaction',
      network: 'Réseau',
      networkFee: 'Frais de Réseau',
      confirmTransaction: 'Confirmer la Transaction',
      verifyAddress: 'Veuillez vérifier l\'adresse du destinataire. Les transactions ne peuvent pas être annulées.',
      selectContact: 'Sélectionner un Contact',
      searchByUsername: 'Rechercher par nom d\'utilisateur ou nom...',
      noUsersFound: 'Aucun utilisateur trouvé',
      searchForUsers: 'Rechercher des utilisateurs pour envoyer SOL',
      positionQrCode: 'Positionnez le code QR dans le cadre',
      addressScanned: 'Adresse scannée!',
      cameraPermissionRequired: 'L\'autorisation de la caméra est requise pour scanner les codes QR',
      selected: 'Sélectionné',
      paymentTo: 'Paiement à',
      pleaseEnterValidAmount: 'Veuillez entrer un montant valide',
      amountMustBeGreaterThanZero: 'Le montant doit être supérieur à 0',
      insufficientBalanceYouHave: 'Solde insuffisant. Vous avez {{balance}} SOL',
      pleaseEnterRecipientAddress: 'Veuillez entrer une adresse de destinataire',
      invalidSolanaAddress: 'Adresse Solana invalide',
      transactionHistory: 'Historique des Transactions',
      noTransactionsYet: 'Pas encore de transactions',
      noMoreTransactions: 'Plus de transactions',
      swap: 'Échange',
      airdrop: 'Airdrop'
    }
  },
  de: {
    wallet: {
      sendSol: 'SOL Senden',
      availableBalance: 'Verfügbares Guthaben',
      recipientAddress: 'Empfängeradresse',
      enterSolanaAddress: 'Solana-Wallet-Adresse eingeben',
      scanQr: 'QR Scannen',
      contacts: 'Kontakte',
      amountSol: 'Betrag (SOL)',
      memoOptional: 'Notiz (Optional)',
      addNote: 'Notiz hinzufügen...',
      transactionDetails: 'Transaktionsdetails',
      network: 'Netzwerk',
      networkFee: 'Netzwerkgebühr',
      confirmTransaction: 'Transaktion Bestätigen',
      verifyAddress: 'Bitte überprüfen Sie die Empfängeradresse. Transaktionen können nicht rückgängig gemacht werden.',
      selectContact: 'Kontakt Auswählen',
      searchByUsername: 'Nach Benutzername oder Name suchen...',
      noUsersFound: 'Keine Benutzer gefunden',
      searchForUsers: 'Benutzer suchen, um SOL zu senden',
      positionQrCode: 'Positionieren Sie den QR-Code im Rahmen',
      addressScanned: 'Adresse gescannt!',
      cameraPermissionRequired: 'Kameraberechtigung ist erforderlich, um QR-Codes zu scannen',
      selected: 'Ausgewählt',
      paymentTo: 'Zahlung an',
      pleaseEnterValidAmount: 'Bitte geben Sie einen gültigen Betrag ein',
      amountMustBeGreaterThanZero: 'Betrag muss größer als 0 sein',
      insufficientBalanceYouHave: 'Unzureichendes Guthaben. Sie haben {{balance}} SOL',
      pleaseEnterRecipientAddress: 'Bitte geben Sie eine Empfängeradresse ein',
      invalidSolanaAddress: 'Ungültige Solana-Adresse',
      transactionHistory: 'Transaktionsverlauf',
      noTransactionsYet: 'Noch keine Transaktionen',
      noMoreTransactions: 'Keine weiteren Transaktionen',
      swap: 'Tausch',
      airdrop: 'Airdrop'
    }
  },
  zh: {
    wallet: {
      sendSol: '发送 SOL',
      availableBalance: '可用余额',
      recipientAddress: '收款人地址',
      enterSolanaAddress: '输入 Solana 钱包地址',
      scanQr: '扫描二维码',
      contacts: '联系人',
      amountSol: '金额 (SOL)',
      memoOptional: '备注（可选）',
      addNote: '添加备注...',
      transactionDetails: '交易详情',
      network: '网络',
      networkFee: '网络费用',
      confirmTransaction: '确认交易',
      verifyAddress: '请验证收款人地址。交易无法撤销。',
      selectContact: '选择联系人',
      searchByUsername: '按用户名或姓名搜索...',
      noUsersFound: '未找到用户',
      searchForUsers: '搜索用户以发送 SOL',
      positionQrCode: '将二维码放置在框架内',
      addressScanned: '地址已扫描！',
      cameraPermissionRequired: '需要相机权限才能扫描二维码',
      selected: '已选择',
      paymentTo: '付款给',
      pleaseEnterValidAmount: '请输入有效金额',
      amountMustBeGreaterThanZero: '金额必须大于 0',
      insufficientBalanceYouHave: '余额不足。您有 {{balance}} SOL',
      pleaseEnterRecipientAddress: '请输入收款人地址',
      invalidSolanaAddress: '无效的 Solana 地址',
      transactionHistory: '交易历史',
      noTransactionsYet: '暂无交易',
      noMoreTransactions: '没有更多交易',
      swap: '兑换',
      airdrop: '空投'
    }
  },
  ja: {
    wallet: {
      sendSol: 'SOLを送信',
      availableBalance: '利用可能残高',
      recipientAddress: '受取人アドレス',
      enterSolanaAddress: 'Solanaウォレットアドレスを入力',
      scanQr: 'QRスキャン',
      contacts: '連絡先',
      amountSol: '金額 (SOL)',
      memoOptional: 'メモ（任意）',
      addNote: 'メモを追加...',
      transactionDetails: '取引詳細',
      network: 'ネットワーク',
      networkFee: 'ネットワーク手数料',
      confirmTransaction: '取引を確認',
      verifyAddress: '受取人アドレスを確認してください。取引は取り消せません。',
      selectContact: '連絡先を選択',
      searchByUsername: 'ユーザー名または名前で検索...',
      noUsersFound: 'ユーザーが見つかりません',
      searchForUsers: 'SOLを送信するユーザーを検索',
      positionQrCode: 'QRコードをフレーム内に配置',
      addressScanned: 'アドレスがスキャンされました！',
      cameraPermissionRequired: 'QRコードをスキャンするにはカメラの許可が必要です',
      selected: '選択済み',
      paymentTo: '支払先',
      pleaseEnterValidAmount: '有効な金額を入力してください',
      amountMustBeGreaterThanZero: '金額は0より大きくする必要があります',
      insufficientBalanceYouHave: '残高不足。{{balance}} SOLあります',
      pleaseEnterRecipientAddress: '受取人アドレスを入力してください',
      invalidSolanaAddress: '無効なSolanaアドレス',
      transactionHistory: '取引履歴',
      noTransactionsYet: 'まだ取引がありません',
      noMoreTransactions: 'これ以上の取引はありません',
      swap: 'スワップ',
      airdrop: 'エアドロップ'
    }
  },
  ko: {
    wallet: {
      sendSol: 'SOL 보내기',
      availableBalance: '사용 가능한 잔액',
      recipientAddress: '수신자 주소',
      enterSolanaAddress: 'Solana 지갑 주소 입력',
      scanQr: 'QR 스캔',
      contacts: '연락처',
      amountSol: '금액 (SOL)',
      memoOptional: '메모 (선택사항)',
      addNote: '메모 추가...',
      transactionDetails: '거래 세부정보',
      network: '네트워크',
      networkFee: '네트워크 수수료',
      confirmTransaction: '거래 확인',
      verifyAddress: '수신자 주소를 확인하세요. 거래는 취소할 수 없습니다.',
      selectContact: '연락처 선택',
      searchByUsername: '사용자 이름 또는 이름으로 검색...',
      noUsersFound: '사용자를 찾을 수 없습니다',
      searchForUsers: 'SOL을 보낼 사용자 검색',
      positionQrCode: 'QR 코드를 프레임 안에 배치',
      addressScanned: '주소가 스캔되었습니다!',
      cameraPermissionRequired: 'QR 코드를 스캔하려면 카메라 권한이 필요합니다',
      selected: '선택됨',
      paymentTo: '지불 대상',
      pleaseEnterValidAmount: '유효한 금액을 입력하세요',
      amountMustBeGreaterThanZero: '금액은 0보다 커야 합니다',
      insufficientBalanceYouHave: '잔액이 부족합니다. {{balance}} SOL이 있습니다',
      pleaseEnterRecipientAddress: '수신자 주소를 입력하세요',
      invalidSolanaAddress: '유효하지 않은 Solana 주소',
      transactionHistory: '거래 내역',
      noTransactionsYet: '아직 거래가 없습니다',
      noMoreTransactions: '더 이상 거래가 없습니다',
      swap: '스왑',
      airdrop: '에어드롭'
    }
  },
  ar: {
    wallet: {
      sendSol: 'إرسال SOL',
      availableBalance: 'الرصيد المتاح',
      recipientAddress: 'عنوان المستلم',
      enterSolanaAddress: 'أدخل عنوان محفظة Solana',
      scanQr: 'مسح QR',
      contacts: 'جهات الاتصال',
      amountSol: 'المبلغ (SOL)',
      memoOptional: 'ملاحظة (اختياري)',
      addNote: 'إضافة ملاحظة...',
      transactionDetails: 'تفاصيل المعاملة',
      network: 'الشبكة',
      networkFee: 'رسوم الشبكة',
      confirmTransaction: 'تأكيد المعاملة',
      verifyAddress: 'يرجى التحقق من عنوان المستلم. لا يمكن عكس المعاملات.',
      selectContact: 'اختر جهة اتصال',
      searchByUsername: 'البحث بالاسم المستخدم أو الاسم...',
      noUsersFound: 'لم يتم العثور على مستخدمين',
      searchForUsers: 'ابحث عن مستخدمين لإرسال SOL',
      positionQrCode: 'ضع رمز QR داخل الإطار',
      addressScanned: 'تم مسح العنوان!',
      cameraPermissionRequired: 'مطلوب إذن الكاميرا لمسح رموز QR',
      selected: 'محدد',
      paymentTo: 'الدفع إلى',
      pleaseEnterValidAmount: 'يرجى إدخال مبلغ صالح',
      amountMustBeGreaterThanZero: 'يجب أن يكون المبلغ أكبر من 0',
      insufficientBalanceYouHave: 'رصيد غير كافٍ. لديك {{balance}} SOL',
      pleaseEnterRecipientAddress: 'يرجى إدخال عنوان المستلم',
      invalidSolanaAddress: 'عنوان Solana غير صالح',
      transactionHistory: 'سجل المعاملات',
      noTransactionsYet: 'لا توجد معاملات بعد',
      noMoreTransactions: 'لا مزيد من المعاملات',
      swap: 'مبادلة',
      airdrop: 'إيردروب'
    }
  }
}
